---
language: go
dist: xenial
os: linux

addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/libsodium'
    packages:
      - libclang-dev
      - libopus-dev
      - libsodium-dev
      - libvpx-dev

jobs:
  include:
    - go: 1.12.x
      if: type IN (push, api, cron)
    - go: 1.13.x
      if: type IN (push, api, cron)
    - go: 1.14.x
      if: type IN (push, api, cron)
    - go: master

before_install:
  - go get github.com/mattn/goveralls

install:
  # Add libclang's lib directory to search path for Go.
  - export CGO_LDFLAGS="-L`llvm-config-3.8 --libdir`"
  # Install toxcore.
  - git clone https://github.com/TokTok/c-toxcore
  - cd c-toxcore
  - cmake .
  - make -j2
  - sudo make install
  - cd ..
  - sudo ldconfig > /dev/null
  # Install Go packages.
  - go get github.com/bitly/go-simplejson
#  - go get -u github.com/go-clang/v3.8/clang
  - go get github.com/kitech/godsts/maps/hashbidimap
  - go get github.com/kitech/godsts/maps/hashmap
  - go get github.com/kitech/godsts/sets/hashset
  - go get github.com/masatana/go-textdistance
  - go get github.com/sasha-s/go-deadlock
  - go get github.com/streamrail/concurrent-map
  - go get github.com/sysr-q/gopp/gopp
  - go get github.com/xrash/smetrics

script:
#  - go run tools/generrmsg.go > const_auto.go && git diff --exit-code
  - rm tools/generrmsg.go
  - $GOPATH/bin/goveralls -service=travis-ci
